version: '3.8'
services:
  server:
    container_name: node-boilerplate
    restart: always
    build: .
    volumes:
      - ./src:/usr/app/
    ports:
      - "3000:3000"
      - "3010:3010"
    command: npm start
